### ISSUE TITLE
Logo?

### ISSUE THREAD

**Issue by nkkollaw** [nkkollaw/zubr#100]
My dog woke me up at 6:00 again this morning, so I made a logo while I was trying to wake up.

I created it from scratch, so we can use it if we want. Not sure that we need one, though, I thought we could put it in the README.

![logo](https://user-images.githubusercontent.com/999994/28993797-9548954c-79bf-11e7-88f4-e1a1e8e2636f.gif)

**Comment by ddziaduch** [comment]
@nkkollaw that is cool 👍
