### ISSUE TITLE
Provide an extension

### ISSUE THREAD

**Issue by brzuchal** [nkkollaw/zubr#103]
I didn't find a better way for this question. I may have spent some time to implement C ext in an `ext` folder by PR so there also may be the same tests were used to verify compatibility with PHP implementation and I was wondering if this would be an acceptable and desirable solution?

**Comment by brzuchal** [comment]
Although after few thoughts I don't think people would really couple with additional dependency just for fixing naming convention :(

**Comment by nkkollaw** [comment]
The lib should be drop-in and installable via Composer, it should probably be PHP rather than a C extension.

:-)
