### ISSUE TITLE
Travis integration

### ISSUE THREAD

**Issue by radmen** [nkkollaw/zubr#105]
This project contains `.travis.yml` file. @nkkollaw it would be good to enable Travis for it :)

**Comment by nkkollaw** [comment]
Yes, it's very high on my list. I'll assign this task to myself and get it done ASAP.

**Comment by Ayesh** [comment]
We could also use Travis to create a single file containing a "minified" version of the files, it would be great too. Ref #106

**Comment by radmen** [comment]
@Ayesh if it's possible then yes - would be super useful.

**Comment by nkkollaw** [comment]
I'll enable Travis tonight and add a script to concatenate everything into 1 file.

**Comment by nkkollaw** [comment]
I've setup Travis CI and builds run at pull requests. We can optionally make it run at changes to branch, what do you guys think?

Otherwise I'll close this.
