### ISSUE TITLE
Implement validator tool

### ISSUE THREAD

**Issue by nkkollaw** [nkkollaw/zubr#117]
I think it might be possible to create some sort of tool that sorted out "good" functions from "bad" ones, and automatically generated code for the good ones so that we didn't have to add them manually.

I'll trying figuring out if it can be done somewhat reliably and create a branch or even another repo that anyone is welcome to contribute to if possible.

In the meantime, I think it would make sense to only add functions that need changes over the original.

**Comment by ddziaduch** [comment]
@nkkollaw what about creating a map of bad functions? We will proxy it - all others should be proxied by generator script

**Comment by nkkollaw** [comment]
Yes. Definitely.

I'm thinking about tools to automate as much as possible. Give me another day or two and I'll get back to you guys with something more concrete.

In the meantime I think we should wait before we add any new code.

Hopefully automation will drastically speed up the process.
