### ISSUE TITLE
Automate adding functions and tests

### ISSUE THREAD

**Issue by nkkollaw** [nkkollaw/zubr#118]
So.

There's this project called Locutus that has already rewritten all core PHP functions in JavaScript, as well as built tests: https://github.com/kvz/locutus, and tests are here: https://github.com/kvz/locutus/tree/master/test/languages/php.

I've found Locutus after a long search and after having examined many libraries to see if there was a way that would help us speed up the process.

I want to create a tool to create stubs for all functions automatically, as well as convert Locutus's tests to PHP so that we don't have to write them from scratch, but merely check if they're correct.

I'll have a first version of this tool ASAP, so that we can look at it together as improve it if desired.

In the meantime I would suggest we don't add any code, to see what comes out of this and take it from there. I think having half-implemented code would be a great start, otherwise reaching version 1.0 would take years.

I'll report back as soon as I have some news.

**Comment by nkkollaw** [comment]
I'm implementing a little utility to extract functions from PHPStorm stubs, and tests from the Locutus project.

Here is the branch: https://github.com/nkkollaw/zubr/tree/20170813-stubs

My goal is to have function stubs in separate PHP files that we can just add to, and working tests.

I'll report back when I'm done, hopefully between tomorrow or the day after tomorrow.

**Comment by nkkollaw** [comment]
I've managed to finish up a rather primitive script that adds stubs for src files as well as tests, and copies tests from Locutus so that one can copy them and reimplement them in PHP without starting from scratch.

The branch is this one: https://github.com/nkkollaw/zubr/tree/20170813-stubs. You can see generated source files here: https://github.com/nkkollaw/zubr/tree/20170813-stubs/src, and generated test stubs here: https://github.com/nkkollaw/zubr/tree/20170813-stubs/tests.

All files have the extension `.TODO`. I think we can use them as a start, and when one is done with rename `.php.TODO` into `.php`.

@radmen + @ddziaduch, what do you think? I can merge the utility as well as the generated files, or we can of course update the script to change what gets generated. Or, we don't use any of it.

Let me know!

**Comment by ddziaduch** [comment]
Hi. I will review this tomorrow:)

**Comment by nkkollaw** [comment]
Awesome!

**Comment by radmen** [comment]
Nice work! Adding stubs as *.TODO files are quite clever.

LGTM 👍

**Comment by nkkollaw** [comment]
Thanks.

I hope we can save some time, I think we can automate writing tests completely, but I didn't have a lot more time to look into that.

**Comment by nkkollaw** [comment]
Hey guys (@radmen @ddziaduch), should I go ahead with this?

I'm not happy about not automating tests, but we can always improve the thing later, since generated files are easily distinguishable thanks to the .TODO extension.

**Comment by radmen** [comment]
Do it ;)

**Comment by nkkollaw** [comment]
Awesome. @ddziaduch..? If anything can you take care of tests, and I'll do functions and different kinds of documentation?

**Comment by ddziaduch** [comment]
This is awesome! All seems fine for me :). We can automate tests in new issue

**Comment by nkkollaw** [comment]
Merged.

I'll keep this open until we figure out tests (which might mean leaving as is, not sure).
