### ISSUE TITLE
Remove dist folder?

### ISSUE THREAD

**Issue by GRiMe2D** [nkkollaw/zubr#137]
I think we should remove `dist/` folder from the repo and should be ignored.

Instead, we could build every week and release them using "Github releases" like Atom [does](https://github.com/atom/atom/releases)

**Comment by nkkollaw** [comment]
Yes, I was actually thinking the same thing yesterday.

It could be included only in releases (although I don't know about every week vs. actual point releases).

Any downside to keeping it, though..?

**Comment by GRiMe2D** [comment]
> Any downside to keeping it, though..?

If we decide to keep it, we should build project everytime when we commit.

**Comment by nkkollaw** [comment]
Yes, that's true.

It's as easy as running this, though (from the command line):

    php build.php

**Comment by GRiMe2D** [comment]
Yes, it's easy to build, but it's also easy to forget when commiting.

My point is **generated** or **built** files which is **not edited by developers** shouldn't be included in repo. Every developer who wants to use this library can **build** it himself.

Of course, there are many repositories in github, where generated files are also included. And as I see, there're no downsides about it.

To keep or not - it's your choice. But I think, you got my point.

**Comment by nkkollaw** [comment]
One good way to do it would be using Travis, so that it's done automatically. I think it's fine if we remove it, and just build when we release a release.

**Comment by nkkollaw** [comment]
If you send a pull request I'll merge the change. Closing.
