### ISSUE TITLE
No tests?

### ISSUE THREAD

**Issue by radmen** [nkkollaw/zubr#2]
I know that this library may be considered "just" a wrapper. Yet the lack of tests disturbs me a little.

Should they be included?

**Comment by szepeviktor** [comment]
Should be a must for every PR.

**Comment by nkkollaw** [comment]
I would have to agree. Does anyone feels like having a go at it..?

**Comment by ghost** [comment]
@radmen @szepeviktor @nkkollaw what about Kahlan? It allows to stub on php function so it will be easy to test whether functions are proxing the valid php functions. I can wrote some tests today

**Comment by nkkollaw** [comment]
Fine with me. :-)

**Comment by radmen** [comment]
@damian-dziaduch-gforces Kahlan looks like an interesting choice. I've no experience with this tool, yet if you will prepare an example I'd gladly use it ;)

**Comment by nkkollaw** [comment]
PHPUnit might work as well..?

**Comment by radmen** [comment]
AFAIR PHPUnit is not able to mock native functions.

As I see it we have two options
1. find something that can mock native functions and write tests based on that (eg. Kahlan)
2. write tests which simply compare results of wrapper with native functions

Ad. 1 
I think this is safer - if mocking library works as intended we will make sure that wrapper function calls the correct function with correct arguments passed.

Ad. 2
This option is less secure - we're checking only results of calls, so it's possible that wrapper function may work in a different matter as wrapped function.

**Comment by nkkollaw** [comment]
I vote for option 1.

**Comment by nkkollaw** [comment]
So, this is where we got to so far:

@damian-dziaduch-gforces  says: Kahlan stubs on php functions works only when you test psr0 / psr4 classes - it mocks composer autoloader. So it will not work with functions

@radmen says: In this case, we can simply create a class with static methods instead of separate functions.

@radmen , that would mean that you like `\PHP\PHP::str_pos()` better than `\PHP\str_pos()`, or would you create a wrapper class that just called the function to make Kahlan work?

**Comment by radmen** [comment]
> that would mean that you like \PHP\PHP::str_pos() better than \PHP\str_pos(), or would you create a wrapper class that just called the function to make Kahlan work?

I'd create wrapper class only to make Kahlan work :)

Yet, writing a god class (with lots of LOC) is not a good idea. After some time it may be hard to maintain.

Regarding limitations of Kahlan I'm suggesting to keep writing plain wrapper functions and test them with PHPUnit (comparing results of wrapper and wrapped function). 

As I imagine the code will go through code-review so we can assume that reviewer will take care of checking if the wrapper is calling the correct function.

**Comment by nkkollaw** [comment]
@radmen : That sounds good to me. Can you create a stub/example and add it to a CONTRIBUTE.md file? You know more about tests than I do. Also, should I add you as a collaborator?

**Comment by radmen** [comment]
@nkkollaw I'm not very good at writing docs. If possible I'd like to leave writing `CONTRIBUTE.md` to you :)

However, I can create a simple foundation for development - basic structure, one (or two) functions with tests etc. 

> Also, should I add you as a collaborator?

That's much of responsibility ;) I don't know for now if I'll have enough time for such thing. IMO let's keep things as they are right now.

**Comment by nkkollaw** [comment]
> However, I can create a simple foundation for development - basic structure, one (or two) functions with tests etc.

That would be absolutely great. I'll then write the documentation.

**Comment by nkkollaw** [comment]
Closing this since we now have tests thanks to @radmen (https://github.com/nkkollaw/php/pull/89).
