### ISSUE TITLE
Workflow

### ISSUE THREAD

**Issue by nkkollaw** [nkkollaw/zubr#20]
To get to version 1.0, we have to add all functions that a default PHP installation comes with (we'll think about extensions in the future, perhaps via a plugin system).

The most comprehensive list I could find is this: http://php.net/manual/en/extensions.membership.php

We would have to support all functions under "Core" (http://php.net/manual/en/extensions.membership.php#extensions.membership.core), and "Bundled" (http://php.net/manual/en/extensions.membership.php#extensions.membership.bundled).

I'm adding each function as an issue, so that whoever implements it can reference the issue while committing or doing pull requests.

I think we should do 1 function per commit/request, referencing the issue.

Would this work in your opinion?

**Comment by radmen** [comment]
> We would have to support all functions under "Core" 

As I understand some of the functions will be just passing arguments to the wrapped functions without any change?

Second question - should we put functions under `core` NS? It would make sense if we'd like to add wrappers for extensions (eg `php\mysql\connect` / `php\mysql\mysql_connect`)?

> I'm adding each function as an issue, so that whoever implements it can reference the issue while committing or doing pull requests.

Good idea. Also it would be good to add those issues to the milestone.

> I think we should do 1 function per commit/request, referencing the issue.

+1

**Comment by nkkollaw** [comment]
> As I understand some of the functions will be just passing arguments to the wrapped functions without any change?

Yes, we're "guaranteeing" that all functions follow the rules set in our guidelines, but if core PHP functions already do, we're simply calling them without intervening in any way.

> Second question - should we put functions under core NS? It would make sense if we'd like to add wrappers for extensions (eg php\mysql\connect / php\mysql\mysql_connect)?

IMHO, neither `php\mysql\connect` nor `php\mysql\mysql_connect`.  I think that for a developer whose been using MySQL functions like `mysql_query`, `mysql_connect` the best, most intuitive thing would be to find their equivalents in `\phpsane\mysql_query` and `\phpsane\mysql_connect`.

> Good idea. Also it would be good to add those issues to the milestone.

Yup, I'm adding all functions and then I'll edit them all at once. Saves time :-)

**Comment by nkkollaw** [comment]
Closing this as workflow is pretty clear by now.
