### ISSUE TITLE
No name?

### ISSUE THREAD

**Issue by nkkollaw** [nkkollaw/zubr#5]
Although the namespace should IMHO be called PHP for clarity and readability, I think the project should have a somewhat recognizable name/repo name.

Even something like PHP-sane or PHP-wrapper.

Opinions..?

**Comment by ddziaduch** [comment]
good idea

**Comment by radmen** [comment]
> Although the namespace should IMHO be called PHP for clarity and readability

There may be a problem with that. On Internals there was a [discussion](https://externals.io/message/98218#98267) about putting core functions to `php` NS. End conclusion is that there won't be any `php` global ns, however some extensions might get it (eg `php\ast`).

Maybe we should follow this convention and ns functions under something like: `php\sane`?

**Comment by nkkollaw** [comment]
> There may be a problem with that. On Internals there was a discussion about putting core functions to php NS. End conclusion is that there won't be any php global ns, however some extensions might get it (eg php\ast).

Good catch. From what I understand they're postponing the issue to PHP 8, though.

> Maybe we should follow this convention and ns functions under something like: php\sane?

That's not bad at all. I also wouldn't hate something like `PHPX`, like `\PHPX\str_pos()` of course we could call it whatever we want, then one can use the namespace as \PHP or whatever (we could make calling it PHP or whatever else a best practice). 

As for "sane", it makes sense but it's somewhat offensive to PHP and PHP devs? Like PHP itself is insane... I would probably personally like something where "wrapper" was the keyword, better.

**Comment by radmen** [comment]
> As for "sane", it makes sense but it's somewhat offensive to PHP and PHP devs? Like PHP itself is insane...

Ah, that's true ;)

You were relating in README to phpsadness - maybe the name should be somehow related to it (eg `php\medicine`) - cure for your PHPSadness :D

**Comment by nkkollaw** [comment]
> You were relating in README to phpsadness - maybe the name should be somehow related to it (eg php\medicine) - cure for your PHPSadness :D

Haha, that's not bad at all. That would mean that PHP devs are sick people at that point, though :D

**Comment by radmen** [comment]
> That would mean that PHP devs are sick people at that point, though :D

I think that our community has sense of humor ;)

Regarding naming - I've recently worked on https://github.com/baethon/phln/ and one thing I can say is that it would be good that the namespace is not too long. If it will be too long there will be temptation to import functions, which will lead to bigger mess :)

I'd suggest using `medicine` (or smth similar) as a main namespace (instead `php`). So that all functions are like `medicine\array_search()`.

**Comment by nkkollaw** [comment]
> I'd suggest using medicine (or smth similar) as a main namespace (instead php). So that all functions are like medicine\array_search().

Sure, let's think about it, though. Many people dismiss projects just for the name.

How about:
- Pill (means "medicine")
- Lek ("medicine" in Polish, but doesn't make a lot of sense in this case)

I'll think of more names. I'm not good at finding names but I'm good at having the impression that one is not the right one :-)

Also it should "look good" when typed, like:

```php
\Pill\str_pos($wha, $ye);
\Lek\str_pos($wha, $ye);
```

EDIT: 2 good ones (IMHO):
phew - Used to express relief, pron. like "few"
phat - Cool, pretty hot, pron. like "fat"

I like Pill, Phat (althought there's already https://github.com/ryanve/phat), and Phew (although there's already https://github.com/vaibhavpandeyvpz/phew).

**Comment by nkkollaw** [comment]
@radmen , since you were saying we mentioned phpsadness, how about "Happy"?

```php
\Happy\str_pos('hello', 'hell');
```
I like it a lot right now (not sure if I'll still like it in a hour or day).

**Comment by radmen** [comment]
`Happy` is kind of nice :) `Pill` is also good (even better). I'm leaving this to you :)

**Comment by nkkollaw** [comment]
No love for `Phew`..?

**Comment by radmen** [comment]
> No love for Phew..?

Lots :) However, this namespace is taken by another package. I'm not sure if it's a good idea to use it in a different one.

**Comment by nkkollaw** [comment]
(last message and then I'm done for today)

Zubr.

This is my list in order of preference:

```
\Zubr\str_pos('Hello', 'What');
\Phew\str_pos('Hello', 'What');
\Happy\str_pos('Hello', 'What');
\Pill\str_pos('Hello', 'What');
```

I think we should go with Phew, because it kinds of remind of "PHP", is short, has meaning. If not, I vote for Zubr because everyone is in Poland, it's short, looks good in monospaced font, and the name doesn't matter unless it's PHPhiphippo.

**Comment by radmen** [comment]
`Zubr` like the polish vodka? I like it ^^

**Comment by nkkollaw** [comment]
Yes, Żubr like the beer or animal :-)

**Comment by nkkollaw** [comment]
Going with Zubr.

🇵🇱
