### ISSUE TITLE
Core/Array: each

### ISSUE THREAD

**Issue by nkkollaw** [nkkollaw/zubr#65]

**Comment by Petah** [comment]
Why only deprecate PHP 5 methods, when this is a clear example of a seldom used, and confusing, method that is deprecated in PHP 7.2

**Comment by nkkollaw** [comment]
Every core PHP function that is present in PHP 7.0.0 will be present in Zubr, no matter how questionable. 

This ensure predictability of the API.

Closing this as this has been reiterated multiple times.
