### ISSUE TITLE
Core/Array: list

### ISSUE THREAD

**Issue by nkkollaw** [nkkollaw/zubr#73]

**Comment by Petah** [comment]
As per commented, this should be excluded?

**Comment by nkkollaw** [comment]
@Petah has correctly brought to my attention, `list` is not a function, but a language construct. For this reason it should therefore NOT be included in Zubr.

Same thing for `array`.

**Comment by nkkollaw** [comment]
@Petah yes—thanks for reporting that, I just left a comment about it and am closing the issue.
