### ISSUE TITLE
Rename lib

### ISSUE THREAD

**Issue by nkkollaw** [nkkollaw/zubr#90]
So, tempted to go with Zubr for the name of the project, as mentioned.

Reasons are (in no particular order):

- current contributors are all in Poland, żubr means buffalo and Żubr is a beer brand and who doesn't like beer
- nice and short
- namespace is available
- looks good: \Zubr\str_pos()

Proceed..?

**Comment by ddziaduch** [comment]
@nkkollaw  IMO that is not a good idea ;) We all use here English, both in code code and GitHub. Why don't we stick with it?

**Comment by ddziaduch** [comment]
@nkkollaw I have an idea. We are fighting with sadness so maybe - PHP + Happines = Phpness or PHPappines   :D

**Comment by nkkollaw** [comment]
> @nkkollaw IMO that is not a good idea ;) We all use here English, both in code code and GitHub. Why don't we stick with it?

Well, a name is a name. If the library is useful, people will find it and use it. Zubr has a meaning because it's related to Poland, for English-speakers it's a made-up word like Google, Yahoo, Etc.

I think it's good enough for now. Options so far are (see #5 for details):

```
\Zubr\str_pos('Hello', 'What');
\Phew\str_pos('Hello', 'What'); // namespace taken by other lib (although not in the same space)
\Happy\str_pos('Hello', 'What');
\Pill\str_pos('Hello', 'What');
\Phpness \str_pos('Hello', 'What'); // too long to type IMHO?
PHPappines\str_pos('Hello', 'What'); // too long to type IMHO?
```

I still think it's either Zubr, or Phew even if the namespace is taken. :-)

**Comment by ddziaduch** [comment]
Ok let's go with Zubr :)

**Comment by nkkollaw** [comment]
Phew is cool, too IMHO. Not sure if the fact that the namespace is taken will ever be a problem, but I doubt it.

The thing with Phew is that it kinds of look like "PHP", so if you see

    \Phew\str_pos()

it's kind of intuitive that it's a PHP wrapper.

**Comment by nkkollaw** [comment]
Closing this as we're going with Zubr.
