### ISSUE TITLE
Project description

### ISSUE THREAD

**Issue by nkkollaw** [nkkollaw/zubr#92]
We need a short description for the project that can quickly convey what we're trying to do.

Current one is:

> A wrapper library to fix inconsistencies in PHP's core functions.

Is it clear what it does? What would work better?

**Comment by ddziaduch** [comment]
"A PHP's core functions beautifier" ?

**Comment by nkkollaw** [comment]
Very nice.

**Comment by nkkollaw** [comment]
Changed it.

Will close this. Good suggestion, @ddziaduch!
